# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:b2hf8gllon7iKzbxsxBsTnR2H7SnveET0EeEhUbw2+CG2ZcyZLFPu+LFOh3N+MZUCp4A5K9QUCnrb7A1iCmkKvwT4GJLi1h1nUKfc/1Va2+sKyACet4BfCMnvQlttqtgrzoO0CuRenSOLX9iSbykiBlf6QtMPJhnUgh1uL65r33014hx6j69ESMOEn+0NivW5NAb3SrQvM73J529IUHXgBu8iYvvEI7uCwTi4uKlk1mW7E8XIw==,iv:03TSvJNbsdLb2VX9G0277DUPqFgMbctFv+TKS3fdRDw=,tag:nkKYJi6stVe0LVgcs5jFiQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16a3eqx6ahtdh8qtvyvv69z5dcd37fggus664rftytwzcvye3v36s50d7s2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVEJ4bkllRE5Nbkl4YnJR
        dHVRaHRGT1lSMEV5SEVSM3RvODR1d3l5UGo0CmlmOVM3ODVxOVhyRXpjNGZHbUF3
        M3N6UXVhaHlMZFZPQTdYQnZnd2gzcTgKLS0tIGpzVVdkZjNrMDhhVkNaOXdhY2hM
        cSthWTRmejRPWTJpOGRZanU3aHdIbUUKc8LqlaEq+UmXu7e3H8rGITs324VePZ/Y
        wIMOJ7ussBdXEW+Bna6SvAY3NAPirmiygjy6RkiuMjCpwt3/Nb34Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-24T03:44:37Z"
  mac: ENC[AES256_GCM,data:qUkLIurAGgUJrkdQ2B/J+jdJXzBp68BEc8ejdGJ6c8jxttstyTOwVeo47Le9ZgLip2WafkHvp8QRJPcMsUBkAopN+mQqGTCfLPewAKzG7bLfyvSUZ0z2pXU1x3YJ5Vd/0C74nI2nMYC02WuYvyMQG6VqfECadCBNEFi2DUi93uo=,iv:NUiqYjzgCcouj/p1uiecEfhIYMLto1YW7ipfJpAUHG8=,tag:6AbJbOzV2VALoYZHWgnuHw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
