apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/apps/longhorn"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
